[package]
name = "preprompt-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
clipboard = "0.5.0 "
structopt = "0.3"
infer = "0.15.0"
mime_guess = "2.0.4"
ignore = "0.4.20"
